spring.application.name=shopflower

spring.datasource.url=jdbc:mysql://localhost:3306/shopflower
spring.datasource.username=root
spring.datasource.password=Dai121298

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# show cau truy van

jwt.signerKey=I4awcIbwN5ySUbGBPk8VvvTg+c4pqlvVN3cgGBk5R38//KFG2TaCW3WzEUBNRvVs
