spring.application.name=shopflower

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

frontend_user.url=${FRONTEND_USER_URL}
frontend_admin.url=${FRONTEND_ADMIN_URL}

spring.jpa.hibernate.ddl-auto=validate

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# show cau truy van

jwt.signerKey=${JWT_SIGNER_KEY}
jwt.valid-duration=${JWT_VALID_DURATION}
jwt.refreshable-duration=${JWT_REFRESHABLE_DURATION}

app.media.url-prefix=${APP_MEDIA_URL_PREFIX}
app.media.max-size=${APP_MEDIA_MAX_SIZE}

vnpay.tmn-code=${VNPAY_TMN_CODE}
vnpay.secret-key=${VNPAY_SECRET_KEY}
vnpay.pay-url=${VNPAY_PAY_URL}
vnpay.return-url=${VNPAY_RETURN_URL}
vnpay.ipn-url=${VNPAY_IPN_URL}
